"""Roll the ledger up to months and emit the file the dashboard reads."""

from __future__ import annotations

import calendar
import json
from datetime import date
from pathlib import Path

from .parsers import Txn

MONTH_NAMES = ["January", "February", "March", "April", "May", "June",
               "July", "August", "September", "October", "November", "December"]


def month_span(first: date, last: date):
    y, m = first.year, first.month
    while (y, m) <= (last.year, last.month):
        yield y, m
        m += 1
        if m == 13:
            y, m = y + 1, 1


def build(txns: list[Txn], categories: list[str], net_worth_start: float,
          today: date | None = None) -> dict:
    today = today or date.today()
    dated = [t for t in txns if t.kind in ("spend", "income")]
    if not dated:
        return {"months": [], "cats": categories, "netWorthStart": net_worth_start,
                "accounts": [], "txns": [], "generatedAt": today.isoformat()}

    first = min(t.date for t in dated)
    last = max(max(t.date for t in dated), today)

    months = []
    for y, m in month_span(first, last):
        spend = {c: 0.0 for c in categories}
        income = 0.0
        count = 0
        for t in dated:
            if t.date.year != y or t.date.month != m:
                continue
            count += 1
            if t.kind == "income":
                income += -t.amount           # stored as a negative outflow
            else:
                spend[t.category if t.category in spend else "Uncategorized"] += t.amount

        is_current = (y, m) == (today.year, today.month)
        entry = {
            "key": f"{y}-{m:02d}",
            "label": f"{MONTH_NAMES[m - 1]} {y}",
            "short": MONTH_NAMES[m - 1][:3] + ("" if y == today.year else f" '{str(y)[2:]}"),
            "income": round(income, 2),
            "spend": {k: round(v, 2) for k, v in spend.items()},
            "txCount": count,
        }
        if is_current:
            entry["current"] = True
            entry["dayOfMonth"] = today.day
            entry["daysInMonth"] = calendar.monthrange(y, m)[1]
        months.append(entry)

    # Drop leading months that have nothing in them at all.
    while months and months[0]["txCount"] == 0:
        months.pop(0)

    # Only show categories that were actually used, keeping settings.json order.
    used = [c for c in categories if any(mo["spend"].get(c, 0) for mo in months)]
    for mo in months:
        mo["spend"] = {c: mo["spend"].get(c, 0.0) for c in used}

    accounts = sorted({t.account for t in txns if t.kind == "spend"})

    # Per-transaction detail backing the "This month" category drill-down.
    # Keys kept short (m/c/d/n/a/acct) since this list can run to several hundred rows.
    txn_detail = [
        {
            "m": f"{t.date.year}-{t.date.month:02d}",
            "c": t.category,
            "d": t.date.isoformat(),
            "n": t.description,
            "a": round(t.amount, 2),
            "acct": t.account,
        }
        for t in txns if t.kind == "spend"
    ]
    txn_detail.sort(key=lambda r: r["d"], reverse=True)

    return {
        "generatedAt": today.isoformat(),
        "netWorthStart": net_worth_start,
        "cats": used,
        "accounts": accounts,
        "months": months,
        "txns": txn_detail,
    }


def write_dashboard_data(data: dict, path: Path) -> None:
    """Plain <script> assignment, so the dashboard opens from file:// with no server."""
    path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(data, indent=1)
    path.write_text(
        "// Generated by build.py — do not edit. Re-run `python3 build.py` instead.\n"
        f"window.FINANCE_DATA = {body};\n",
        encoding="utf-8",
    )
